### ISSUE TITLE
[Bug]: Some files can not be watched in development mode

### ISSUE THREAD

**Issue by BillNotOnly666** [weapp-vite/weapp-vite#27]
### version

1.4.1

### Link to minimal reproduction

no link available

### Steps to reproduce

create a simple demo, with new a app entry file 'app.ts'. Start the dev mode with 'npm run dev'. Then modify app entry file, the vite build tool could not build automatic after app entry file modified.

### What is expected?

create a simple demo, with new a app entry file 'app.ts'. Start the dev mode with 'npm run dev'. Then modify app entry file, the vite build tool could build automatic after app entry file modified.

### What is actually happening?

Start the dev mode with 'npm run dev'. Then modify app entry file, the vite build tool could not build automatic after app entry file modified.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 115.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 6.11.0 - /usr/local/bin/pnpm
  npmPackages:
    less: ^4.2.0 => 4.2.0 
    lodash: ^4.17.21 => 4.17.21 
    miniprogram-api-typings: latest => 4.0.1 
    typescript: latest => 5.6.2 
    vite: ^5.4.8 => 5.4.8 
    vite-plugin-inspect: ^0.8.7 => 0.8.7 
    weapp-vite: latest => 1.4.1
```

### Any additional comments?

I try to read the source code and get some information about the tool's config. It seems the chokidar received a wrong ignored value in runDev method, line 121 in context file. The 'mpDistRoot' field is empty default, so chokidar watcher received '**'.

**Comment by sonofmagic** [comment]
这个问题在新版本修复了
