### ISSUE TITLE
[Bug]: theme.json 无法打包到dist 目录下

### ISSUE THREAD

**Issue by daguanren21** [weapp-vite/weapp-vite#29]
### version

1.4.5

### Link to minimal reproduction

https://github.com/daguanren21/mininal-weap-vite

### Steps to reproduce

native-ts miniprogram 目录下配置theme.json 执行 weapp-vite dev 发现 dist 目录下没有 theme.json 文件

### What is expected?

 dist 目录下有 theme.json 文件

### What is actually happening?

dist 目录下没有 theme.json 文件

**Comment by sonofmagic** [comment]
是的，这是一个已知问题，目前  theme.json 和 sitemap.json 暂时都不许，马上修好
目前暂时可以通过 https://www.npmjs.com/package/vite-plugin-static-copy 这个 vite 插件来解决这个问题
```js
   viteStaticCopy({
        targets: [
          {
            src: 'path/to/theme.json',
            dest: '.',
          },
        ],
      }),
```

**Comment by sonofmagic** [comment]
已在 [weapp-vite@1.5.2](https://github.com/weapp-vite/weapp-vite/releases/tag/weapp-vite%401.5.2) 版本中修复

现在会根据 app.json 里的 sitemapLocation 和 themeLocation 地址，自动来进行拷贝和粘贴
