### ISSUE TITLE
[Bug]: appBar 文件缺失

### ISSUE THREAD

**Issue by F-loat** [weapp-vite/weapp-vite#47]
### version

1.6.8

### Link to minimal reproduction

https://github.com/F-loat/xiaoplayer

### Steps to reproduce

``` sh
npx weapp-vite create my-app
cd my-app
echo "{}" > ./src/app-bar/index.json
echo "<view>test</view>" > ./src/app-bar/index.wxml
echo "Component({})" > ./src/app-bar/index.ts
sed -i '' 's/window/appBar/g' src/app.json
pnpm i
pnpm build
```

### What is expected?

dist/app-bar 目录中生成 json/wxml/js 三个文件

### What is actually happening?

dist/app-bar 目录中只生成了 wxml 一个文件

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 103.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: 8.6.11 - /opt/homebrew/bin/pnpm
  npmPackages:
    @egoist/tailwindcss-icons: ^1.8.1 => 1.8.1 
    @iconify-json/mdi: ^1.2.1 => 1.2.1 
    autoprefixer: ^10.4.20 => 10.4.20 
    miniprogram-api-typings: latest => 4.0.1 
    postcss: ^8.4.47 => 8.4.47 
    sass: ^1.80.2 => 1.80.2 
    tailwindcss: ^3.4.14 => 3.4.14 
    typescript: latest => 5.6.3 
    weapp-tailwindcss: latest => 3.6.2 
    weapp-vite: latest => 1.6.8
```

**Comment by sonofmagic** [comment]
这个假如是一个组件/页面的话，其实是需要添加到 `app.json` 或者其他的 `json` 文件里面，进行引用的。
weapp-vite 会通过 `app.json` / 其他的 `json` 里的 `usingComponents` 字段，去寻找依赖。

你这个 `app-bar` 组件，被其他的组件引用了嘛？或者是直接作为 page 在 json 中进行注册了嘛？

**Comment by F-loat** [comment]
@sonofmagic 少写了一行，要在 app.json 中配置 `appBar: {}` 启用这个功能的，[全局工具栏](https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/appbar.html)

**Comment by F-loat** [comment]
这个功能之前是好使的，不太确定哪一版出的问题

**Comment by sonofmagic** [comment]
懂了，我之前只是支持了 `custom-tab-bar` ，没有注意到新加的 `app-bar` 这个也是和这个一样，也是全局的
这个我稍后加一下
https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/appbar.html

**Comment by sonofmagic** [comment]
在 `1.6.9` 版本的 `weapp-vite` 中，已经支持了 `app-bar`，可以试试

**Comment by F-loat** [comment]
@sonofmagic 可以了
