### ISSUE TITLE
[Bug]: 打包产物应该是 app.wxss，但输出却是 app-[hash].css

### ISSUE THREAD

**Issue by Hongbusi** [weapp-vite/weapp-vite#6]
### version

1.1.5

### Link to minimal reproduction

无

### Steps to reproduce

1. 更新依赖

<img width="899" alt="image" src="https://github.com/user-attachments/assets/6c522a24-9c80-4535-b91d-a607907c9ed1">

3. 执行 `dev/build`

<img width="543" alt="image" src="https://github.com/user-attachments/assets/a883bfd7-939c-401f-9ba3-bcb0689943e3">
 

### What is expected?

应输出 `app.wxss`

### What is actually happening?

`app.wxss` 输出为 `app-[hash].css` 文件

**Comment by sonofmagic** [comment]
fixed in `1.1.6`
