### ISSUE TITLE
[Bug]: The related dependencies package is missing after installing the miniprogram-computed

### ISSUE THREAD

**Issue by MrHeer** [weapp-vite/weapp-vite#65]
### version

1.7.8

### Link to minimal reproduction

Noop

### Steps to reproduce

1. Install `miniprogram-computed`
2. [Use computed value](https://github.com/wechat-miniprogram/computed?tab=readme-ov-file#computed-%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95)
3. Build and Run

### What is expected?

It works fine

### What is actually happening?

It can't find dependencies of `miniprogram-computed`

**Comment by sonofmagic** [comment]
这是由于包管理器必须扁平化导致的，详见 https://github.com/wechat-miniprogram/computed/issues/87
你可以通过再安装 `fast-deep-equal` 和 `rfdc` 来解决这个问题：

```sh
pnpm add miniprogram-computed fast-deep-equal rfdc
```

然后在代码中使用即可
```ts
import { ComponentWithComputed } from 'miniprogram-computed'
// js 中也可以使用 import { behavior as computedBehavior } from 'miniprogram-computed'
ComponentWithComputed({
  data: {
    a: 1,
    b: 1,
  },
  computed: {
    sum(data) {
      // 注意： computed 函数中不能访问 this ，只有 data 对象可供访问
      // 这个函数的返回值会被设置到 this.data.sum 字段中
      return data.a + data.b
    },
  },
  methods: {
    onTap() {
      this.setData({
        a: this.data.b,
        b: this.data.a + this.data.b,
      })
    },
  },
})

```

**Comment by sonofmagic** [comment]
Fixed in `1.8.1`

**Comment by MrHeer** [comment]
我昨天就是手动安装解决的

**Comment by sonofmagic** [comment]
https://vite.icebreaker.top/integration/miniprogram-computed.html
