### ISSUE TITLE
[Bug]: autoImportComponents没有起作用

### ISSUE THREAD

**Issue by weifeiyue** [weapp-vite/weapp-vite#73]
### version

1.9.1

### Link to minimal reproduction

```ts
import { defineConfig } from 'weapp-vite/config'
export default defineConfig({
  weapp: {
    srcRoot: 'src',
    enhance: {
      autoImportComponents: {
        globs: ['src/components/**/*'],
      },
    }
  }
})
```

### Steps to reproduce

autoImportComponents没有起作用

### What is expected?

autoImportComponents起作用

### What is actually happening?

autoImportComponents没有起作用

**Comment by sonofmagic** [comment]
> [!WARNING]  
> 注意! 自动导入组件这个行为，会自动忽略小程序内置组件标签，比如 `view`, `text`, [`navigation-bar`](https://developers.weixin.qq.com/miniprogram/dev/component/navigation-bar.html) 等等（所有的标签详见 [官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/) ）
> 所以你组件不能起和这些同名! 忽略内建组件的数据详情见 [`builtin.auto.ts` 源代码](https://github.com/weapp-vite/weapp-vite/blob/main/packages/weapp-vite/src/auto-import-components/builtin.auto.ts)

**Comment by sonofmagic** [comment]
是的 `navigation-bar` 是小程序内置组件，用法如下: 
```html
<page-meta>
  <navigation-bar
    title="{{nbTitle}}"
    loading="{{nbLoading}}"
    front-color="{{nbFrontColor}}"
    background-color="{{nbBackgroundColor}}"
    color-animation-duration="2000"
    color-animation-timing-func="easeIn"
  />
</page-meta>
```
所以你组件和这个同名，就被自动忽略了。
相关文档已经补充到 https://vite.icebreaker.top/guide/auto-import.html
