### ISSUE TITLE
[Bug]: 使用 JSON.TS 生成 JSON 时存在的问题

### ISSUE THREAD

**Issue by VicBilibily** [weapp-vite/weapp-vite#75]
### version

weapp-vite@1.9.2(@types/node@20.17.10)(less@4.2.1)(typescript@5.7.2)

### Link to minimal reproduction

https://github.com/VicBilibily/vite-app-demo

### Steps to reproduce

1、当 Component 名称包含 `-` 时产物只生成 `*.wxml`。
> 例如：使用 `navigation-bar.json.ts` 时 `dist` 产物只有 `navigation-bar.xmal`
> 正常：使用 `navigationBar.json.ts` 时产物齐全。

2、使用 autoImportComponents : globs 时自动引入的路径错误。
> 错误：自动引入的路径为 `/components/navigationBar/navigationBar.json`，不应包含 `.json`

### What is expected?

1、当组件名称包含 `-` 连接符时，使用 `json.ts` 应正确生成产物。
2、使用 `json.ts` 并开启自动导入组件时应正确导入组件路径。

### What is actually happening?

如上

**Comment by sonofmagic** [comment]
其实这个问题，引发的原因和 https://github.com/weapp-vite/weapp-vite/issues/73 是一样的，

都是由于 `navigation-bar` 是微信小程序的内置组件，所以 `weapp-vite` 自动导入功能，忽略了 `navigation-bar` 标签，

这导致了 `weapp-vite` 不认为它是一个打包的 `entry`，从而直接跳过了它，只是简单的进行了复制 `wxml` 的行为。

**Comment by sonofmagic** [comment]
https://github.com/weapp-vite/weapp-vite/blob/main/packages/weapp-vite/src/auto-import-components/builtin.auto.ts#L84

**Comment by VicBilibily** [comment]
> 其实这个问题，引发的原因和 #73 是一样的，
> 
> 都是由于 `navigation-bar` 是微信小程序的内置组件，所以 `weapp-vite` 自动导入功能，忽略了 `navigation-bar` 标签，
> 
> 这导致了 `weapp-vite` 不认为它是一个打包的 `entry`，从而直接跳过了它，只是简单的进行了复制 `wxml` 的行为。

原因之一可能是这个，但是后续测试了几个名称带 `-` 字符的，使用 `json.ts` 都只复制了 `xmal`。

[https://github.com/VicBilibily/vite-app-demo/commit/df652c4da0bbb7a5aaa909ff65a73254e81945ca](url)

**Comment by sonofmagic** [comment]
好的，感谢提供demo，我再跑跑试试

**Comment by sonofmagic** [comment]
Fixed in `1.9.3` 版本，可以升级一下

**Comment by VicBilibily** [comment]
> Fixed in `1.9.3` 版本，可以升级一下

第2点验证通过了，自动导入的路径正确了。

第1点的名称带 `-` 的组件在**有明确使用**的情况给下能够正确生成，没有被使用的依然时仅复制`wxml`。

https://github.com/VicBilibily/vite-app-demo/commit/c29b6e9df0d44bba66c5a5e50b91da6ac950124e

**Comment by sonofmagic** [comment]
关于第一点，这是因为目前 weapp-vite 对于 wxml 的处理，就是使用 glob 加载，然后再进行复制，从而生成最后的结果的，所以会有 wxml，因为主要是考虑到 wxml 中的  include 和 import 动态绑定的方式，导致我必须要复制所有的 wxml.
原先我可能是想分析:
```html
<import src="item.wxml"/>
<template is="item" data="{{text: 'forbar'}}"/>

<include src="header.wxml"/>
<view> body </view>
<include src="footer.wxml"/>
```
然后，动态的去拉属性，但是用户还可以这么写
```html
<import src="{{importSrc}}"/>
<template is="item" data="{{text: 'forbar'}}"/>

<include src="{{includeSrc}}"/>
<view> body </view>
```
这种方式，这导致我静态分析就很难了，所以目前的策略是 `wxml` 全部处理+复制的方式

https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html

**Comment by VicBilibily** [comment]
这个只复制了`wxml`的可能在真机会出现问题。
月初维护一个旧项目，发布后客户发现功能异常，检查后发现就算是空页面也要有`.json`文件，否则在真机上这个页面无效。

**Comment by sonofmagic** [comment]
Enhance in `2.0.0`
